# Generated by Django 6.0.2 on 2026-03-11 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_application_caretakerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('grandparent', 'Grandparent'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('other', 'Other')], default='parent', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='', max_length=10)),
                ('medical_conditions', models.TextField(blank=True, default='', help_text='List of medical conditions')),
                ('allergies', models.TextField(blank=True, default='')),
                ('medications', models.TextField(blank=True, default='', help_text='Current medications')),
                ('dietary_restrictions', models.TextField(blank=True, default='')),
                ('mobility_status', models.CharField(choices=[('independent', 'Independent'), ('walker', 'Walker/Cane'), ('wheelchair', 'Wheelchair'), ('bedridden', 'Bedridden')], default='independent', max_length=20)),
                ('cognitive_status', models.CharField(choices=[('normal', 'Normal'), ('mild_impairment', 'Mild Cognitive Impairment'), ('dementia', 'Dementia'), ('alzheimers', "Alzheimer's")], default='normal', max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Any additional notes about the elder')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary elder for quick requests')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='elder_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(limit_choices_to={'role': 'family'}, on_delete=django.db.models.deletion.CASCADE, related_name='elder_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elder Profile',
                'verbose_name_plural': 'Elder Profiles',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='elders',
            field=models.ManyToManyField(blank=True, help_text="Elderly persons under this family's care", related_name='family_profiles', to='Users.elderprofile'),
        ),
    ]
