# Generated by Django 6.0.2 on 2026-04-30 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0010_carebooking_completion_notes_carebooking_start_notes'),
        ('Users', '0003_remove_family_profile_patient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Requests.carebooking'),
        ),
    ]
