# Generated by Django 6.0.2 on 2026-03-11 06:10

from django.db import migrations


def link_elders_to_family_profiles(apps, schema_editor):
    ElderProfile = apps.get_model('Users', 'ElderProfile')
    FamilyProfile = apps.get_model('Users', 'FamilyProfile')
    
    # Counter for tracking
    linked_count = 0
    created_count = 0
    
    # Go through all elders
    for elder in ElderProfile.objects.all():
        try:
            # Try to get existing family profile for this elder's family
            family_profile = FamilyProfile.objects.get(user=elder.family)
            
            # Check if elder is already linked
            if not family_profile.elders.filter(id=elder.id).exists():
                family_profile.elders.add(elder)
                linked_count += 1
                print(f"✓ Linked {elder.name} to {elder.family.username}'s profile")
            else:
                print(f"→ {elder.name} already linked to {elder.family.username}'s profile")
                
        except FamilyProfile.DoesNotExist:
            # Create family profile if it doesn't exist
            family_profile = FamilyProfile.objects.create(
                user=elder.family,
                phone=elder.family.phone or '',
                address='',
                city='',
                state='',
                patient_name='',
            )
            family_profile.elders.add(elder)
            created_count += 1
            print(f"✓ Created profile for {elder.family.username} and linked {elder.name}")
    
    print(f"\nSummary: Linked {linked_count} elders, created {created_count} new family profiles")

def reverse_link(apps, schema_editor):
    # This reverses the operation - removes elders from family profiles
    FamilyProfile = apps.get_model('Users', 'FamilyProfile')
    
    for family_profile in FamilyProfile.objects.all():
        count = family_profile.elders.count()
        family_profile.elders.clear()
        if count > 0:
            print(f"✓ Removed {count} elders from {family_profile.user.username}'s profile")

class Migration(migrations.Migration):
    dependencies = [
        ('Users', '0003_elderprofile_familyprofile_elders'),
    ]

    operations = [
        migrations.RunPython(link_elders_to_family_profiles, reverse_link),
    ]
