# Generated by Django 6.0.2 on 2026-02-26 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('patient_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('medical_condition', models.TextField()),
                ('mobility_status', models.CharField(choices=[('independent', 'Independent'), ('walker', 'Walker/Cane'), ('wheelchair', 'Wheelchair'), ('bedridden', 'Bedridden')], default='independent', max_length=50)),
                ('cognitive_status', models.CharField(choices=[('normal', 'Normal'), ('mild_impairment', 'Mild Cognitive Impairment'), ('dementia', 'Dementia'), ('alzheimers', "Alzheimer's")], default='normal', max_length=50)),
                ('care_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', ' Part Time'), ('night_care', 'Night Care'), ('home_visit', 'Home Visit'), ('emergency', 'Emergency Care'), ('respite', 'Respite Care'), ('palliative', 'Palliative Care'), ('post_surgery', 'Post-Surgery Care')], max_length=50)),
                ('urgency_level', models.CharField(choices=[('low', 'Low - Can wait'), ('medium', 'Medium - Within a week'), ('high', 'High - Within 2-3 days'), ('urgent', 'Urgent - Immediately')], default='medium', max_length=20)),
                ('required_skills', models.TextField(help_text='Comma-separated list of required skills')),
                ('preferred_qualifications', models.TextField(blank=True)),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month')], default='monthly', max_length=20)),
                ('negotiable', models.BooleanField(default=True)),
                ('shift_timing', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration_days', models.IntegerField(help_text='Number of days care is needed')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('days_per_week', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('gender_preference', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male')], default='any', max_length=20)),
                ('age_preference_min', models.IntegerField(blank=True, null=True)),
                ('age_preference_max', models.IntegerField(blank=True, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('special_requirements', models.TextField(blank=True)),
                ('equipment_provided', models.TextField(blank=True, help_text='Medical equipment provided by family')),
                ('accommodation_provided', models.BooleanField(default=False)),
                ('accommodation_details', models.TextField(blank=True)),
                ('interview_required', models.BooleanField(default=True)),
                ('interview_type', models.CharField(choices=[('in_person', 'In Person'), ('video', 'Video Call'), ('phone', 'Phone Call')], default='video', max_length=20)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('under_review', 'Under Review'), ('interviewing', 'Interviewing'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Care Request',
                'verbose_name_plural': 'Care Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='request_docs/')),
                ('description', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareRequestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
