# Generated by Django 6.0.2 on 2026-03-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='assigned_caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carerequestschedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Requests.carerequest'),
        ),
        migrations.AlterUniqueTogether(
            name='carerequestschedule',
            unique_together={('request', 'day_of_week')},
        ),
    ]
