# Generated by Django 6.0.2 on 2026-03-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='care_details',
            field=models.TextField(blank=True, help_text='Detailed description of care requirements', null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text="Emergency contact person's name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carerequest',
            name='care_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_care', 'Night Care'), ('home_visit', 'Home Visit'), ('emergency', 'Emergency Care'), ('respite', 'Respite Care'), ('palliative', 'Palliative Care'), ('post_surgery', 'Post-Surgery Care')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CareRequestDocument',
        ),
    ]
