# Generated by Django 6.0.2 on 2026-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carerequest',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications', null=True),
        ),
    ]
