# Generated by Django 6.0.2 on 2026-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0003_carerequest_allergies_carerequest_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carerequest',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='carerequest',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='carerequest',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='carerequest',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='carerequest',
            name='medications',
        ),
    ]
