# Generated by Django 6.0.2 on 2026-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_remove_carerequest_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequest',
            name='care_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_care', 'Night Care')], max_length=50),
        ),
    ]
