# Generated by Django 6.0.2 on 2026-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0005_alter_carerequest_care_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerequest',
            name='care_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_care', 'Night Care'), ('home_visit', 'Home Visit'), ('emergency', 'Emergency Care'), ('respite', 'Respite Care'), ('palliative', 'Palliative Care'), ('post_surgery', 'Post-Surgery Care')], max_length=50),
        ),
    ]
