# Generated by Django 6.0.2 on 2026-03-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0007_carebooking_caretakeravailability'),
        ('Users', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerequest',
            name='elder_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_requests', to='Users.elderprofile'),
        ),
    ]
