# Generated by Django 6.0.2 on 2026-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0008_carerequest_elder_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='carebooking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carebooking',
            name='confirmation_message',
            field=models.TextField(blank=True),
        ),
    ]
