# Generated by Django 6.0.2 on 2026-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0009_carebooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carebooking',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carebooking',
            name='start_notes',
            field=models.TextField(blank=True),
        ),
    ]
