# Generated by Django 6.0.2 on 2026-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('on_hold', 'On Hold'), ('frozen', 'Frozen'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('no_show', 'No Show'), ('care_started', 'Care Started'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_care', 'Night Care'), ('home_visit', 'Home Visit'), ('emergency', 'Emergency Care')], default='full_time', max_length=20)),
                ('work_start_time', models.TimeField(blank=True, help_text='Start time for part-time jobs', null=True)),
                ('work_end_time', models.TimeField(blank=True, help_text='End time for part-time jobs', null=True)),
                ('work_days', models.JSONField(blank=True, help_text='Array of working days (0-6 where 0 is Monday)', null=True)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('shortlist_notes', models.TextField(blank=True, help_text='Private notes for family about this candidate')),
                ('shortlist_rank', models.IntegerField(blank=True, help_text='Optional ranking of shortlisted candidates', null=True)),
                ('hold_reason', models.TextField(blank=True, help_text='Reason for putting candidate on hold', null=True)),
                ('hold_placed_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_reason', models.TextField(blank=True, help_text='Why this shortlist was frozen', null=True)),
                ('offer_sent_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('offer_declined_at', models.DateTimeField(blank=True, null=True)),
                ('offer_details', models.JSONField(blank=True, help_text='Store final offer details', null=True)),
                ('offer_response_note', models.TextField(blank=True, help_text='Optional note from caretaker when responding to offer')),
                ('care_started_at', models.DateTimeField(blank=True, null=True)),
                ('care_started_by', models.CharField(blank=True, choices=[('family', 'Family'), ('caretaker', 'Caretaker'), ('both', 'Both'), ('auto', 'Auto')], max_length=20, null=True)),
                ('care_start_confirmed_by_family', models.BooleanField(default=False)),
                ('care_start_confirmed_by_caretaker', models.BooleanField(default=False)),
                ('care_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
