# Generated by Django 6.0.2 on 2026-03-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applications', '0001_initial'),
        ('Requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careapplication',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Requests.carerequest'),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['caretaker', 'status'], name='Application_caretak_2f0a79_idx'),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['request', 'status'], name='Application_request_00d4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['status', 'offer_expires_at'], name='Application_status_76bee2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careapplication',
            unique_together={('caretaker', 'request')},
        ),
    ]
