# Generated by Django 6.0.2 on 2026-02-27 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_initial'),
        ('Requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careapplication',
            name='care_start_confirmed_by_caretaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='care_start_confirmed_by_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='care_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='care_started_by',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('caretaker', 'Caretaker'), ('both', 'Both'), ('auto', 'Auto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_details',
            field=models.JSONField(blank=True, help_text='Store final offer details', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='shortlist_notes',
            field=models.TextField(blank=True, help_text='Private notes for family about this candidate'),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='shortlist_rank',
            field=models.IntegerField(blank=True, help_text='Optional ranking of shortlisted candidates', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='careapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('offer_sent', 'Offer Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='careapplication',
            unique_together={('caretaker', 'request')},
        ),
    ]
