# Generated by Django 6.0.2 on 2026-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_careapplication_care_start_confirmed_by_caretaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careapplication',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='frozen_reason',
            field=models.TextField(blank=True, help_text='Why this shortlist was frozen', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='hold_placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason for putting candidate on hold', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='offer_response_note',
            field=models.TextField(blank=True, help_text='Optional note from caretaker when responding to offer'),
        ),
        migrations.AlterField(
            model_name='careapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('on_hold', 'On Hold'), ('frozen', 'Frozen'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
