# Generated by Django 6.0.2 on 2026-03-03 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_careapplication_frozen_at_and_more'),
        ('Requests', '0003_carerequest_care_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careapplication',
            name='care_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('night_care', 'Night Care'), ('home_visit', 'Home Visit'), ('emergency', 'Emergency Care')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='work_days',
            field=models.JSONField(blank=True, help_text='Array of working days (0-6 where 0 is Monday)', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='End time for part-time jobs', null=True),
        ),
        migrations.AddField(
            model_name='careapplication',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Start time for part-time jobs', null=True),
        ),
        migrations.AlterField(
            model_name='careapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('on_hold', 'On Hold'), ('frozen', 'Frozen'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('no_show', 'No Show'), ('care_started', 'Care Started'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['caretaker', 'status'], name='Application_caretak_2f0a79_idx'),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['request', 'status'], name='Application_request_00d4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='careapplication',
            index=models.Index(fields=['status', 'offer_expires_at'], name='Application_status_76bee2_idx'),
        ),
    ]
