# Generated by Django 6.0.2 on 2026-03-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_caregiverreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretask',
            name='escalation_level',
            field=models.IntegerField(default=0, help_text='0: None, 1: Nurse, 2: Family, 3: Admin'),
        ),
        migrations.AddField(
            model_name='caretask',
            name='missed_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caretask',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/proof/%Y/%m/%d/'),
        ),
    ]
