# Generated by Django 6.0.2 on 2026-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_caretask_escalation_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretask',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('in_progress', '🔄 In Progress'), ('completed', '✅ Completed (Action Required)'), ('verified', '🛡️ Verified'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20),
        ),
    ]
