# Generated by Django 6.0.2 on 2026-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('application_shortlisted', 'Application Shortlisted'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('care_started', 'Care Started'), ('care_completed', 'Care Completed'), ('task_assigned', 'Task Assigned'), ('reminder', 'Reminder')], max_length=30),
        ),
    ]
